version: '3'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    env_file:
      - backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - custom


  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - backend/.env
    volumes:
      - media_volume:/backend/media
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - custom


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./devops/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    depends_on:
      - backend
    networks:
      - custom


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - ./devops/grafana.ini:/etc/grafana/grafana.ini
    expose:
      - 3000
    depends_on:
      - backend
      - prometheus
    networks:
      - custom
    user: "0"


  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - custom


  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - media_volume:/backend/media
      - ./devops/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - db
      - redis
      - prometheus
      - grafana
    networks:
      - custom


  bot:
    container_name: bot
    image: bot
    restart: always
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    env_file:
      - bot/.env
    expose:
      - 6000
    depends_on:
      - db
      - backend
      - redis
      - web
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  db-data:
  grafana-data:
  grafana-config:
  prometheus-data:
  media_volume:
