version: '3'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    restart: always
    env_file:
      - src/.env
    expose:
      - 5432
    networks:
      - custom


  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    volumes:
      - media_volume:/src/media
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - custom


  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - custom


  web:
    container_name: web
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - media_volume:/src/media
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - db
      - redis
    networks:
      - custom


networks:
  custom:
    driver: bridge

volumes:
  media_volume:
