"""init

Revision ID: fcf7b96b9fb3
Revises: 
Create Date: 2023-09-11 20:21:45.051144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fcf7b96b9fb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('customer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('street', sa.String(length=50), nullable=False),
                    sa.Column('house', sa.String(length=50), nullable=False),
                    sa.Column('office', sa.String(length=50), nullable=True),
                    sa.Column('metro_station', sa.String(length=50), nullable=True),
                    sa.Column('website', sa.String(length=50), nullable=True),
                    sa.Column('status', sa.Enum('active', 'inactive', name='activestatus'), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_customer_city'), 'customer', ['city'], unique=False)
    op.create_index(op.f('ix_customer_metro_station'), 'customer', ['metro_station'], unique=False)
    op.create_index(op.f('ix_customer_street'), 'customer', ['street'], unique=False)
    op.create_index(op.f('ix_customer_title'), 'customer', ['title'], unique=True)
    op.create_table('manufacturer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('city', sa.String(length=50), nullable=False),
                    sa.Column('street', sa.String(length=50), nullable=False),
                    sa.Column('house', sa.String(length=50), nullable=False),
                    sa.Column('office', sa.String(length=50), nullable=True),
                    sa.Column('metro_station', sa.String(length=50), nullable=True),
                    sa.Column('website', sa.String(length=50), nullable=True),
                    sa.Column('status', sa.Enum('active', 'inactive', name='activestatus'), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_manufacturer_city'), 'manufacturer', ['city'], unique=False)
    op.create_index(op.f('ix_manufacturer_metro_station'), 'manufacturer', ['metro_station'], unique=False)
    op.create_index(op.f('ix_manufacturer_street'), 'manufacturer', ['street'], unique=False)
    op.create_index(op.f('ix_manufacturer_title'), 'manufacturer', ['title'], unique=True)
    op.create_table('permission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('staff_manager',
                    sa.Column('job_title', sa.Enum('intern', 'junior', 'middle', 'senior', name='jobtitle'),
                              nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.Column('second_name', sa.String(length=50), nullable=True),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_staff_manager_email'), 'staff_manager', ['email'], unique=True)
    op.create_index(op.f('ix_staff_manager_phone'), 'staff_manager', ['phone'], unique=True)
    op.create_table('user',
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.Column('second_name', sa.String(length=50), nullable=True),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('customer_manager',
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.Column('second_name', sa.String(length=50), nullable=True),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_customer_manager_email'), 'customer_manager', ['email'], unique=True)
    op.create_index(op.f('ix_customer_manager_phone'), 'customer_manager', ['phone'], unique=True)
    op.create_table('manufacturer_manager',
                    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=50), nullable=True),
                    sa.Column('second_name', sa.String(length=50), nullable=True),
                    sa.Column('last_name', sa.String(length=50), nullable=True),
                    sa.Column('phone', sa.String(length=12), nullable=True),
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('registration_date', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_manufacturer_manager_email'), 'manufacturer_manager', ['email'], unique=True)
    op.create_index(op.f('ix_manufacturer_manager_phone'), 'manufacturer_manager', ['phone'], unique=True)
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('delivery_method', sa.Enum('delivery', 'pickup', name='orderdelivery'), nullable=False),
                    sa.Column('payment_method', sa.Enum('cash', 'card', name='orderpay'), nullable=False),
                    sa.Column('status', sa.Enum('processing', 'done', name='orderstatus'), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('sum_price', sa.Float(), nullable=False),
                    sa.Column('staff_manager_id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.ForeignKeyConstraint(['staff_manager_id'], ['staff_manager.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_order_delivery_method'), 'order', ['delivery_method'], unique=False)
    op.create_index(op.f('ix_order_payment_method'), 'order', ['payment_method'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('permission_user',
                    sa.Column('permission_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('type', sa.Enum('biscuit', 'sandy', 'puff', 'waffle', 'air', 'tiny', 'custards',
                                              name='producttype'), nullable=False),
                    sa.Column('weight', sa.Integer(), nullable=True),
                    sa.Column('best_before_date', sa.Integer(), nullable=True),
                    sa.Column('storage_temperature', sa.Integer(), nullable=True),
                    sa.Column('proteins', sa.Integer(), nullable=True),
                    sa.Column('fats', sa.Integer(), nullable=True),
                    sa.Column('carbohydrates', sa.Integer(), nullable=True),
                    sa.Column('energy_value', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=True)
    op.create_table('category_product',
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
                    )
    op.create_table('image',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    op.create_table('order_product',
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('product_id', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], )
                    )
    op.create_table('review',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('date_in', sa.DateTime(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_review_rating'), 'review', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_rating'), table_name='review')
    op.drop_table('review')
    op.drop_table('order_product')
    op.drop_table('image')
    op.drop_table('category_product')
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_table('product')
    op.drop_table('permission_user')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_payment_method'), table_name='order')
    op.drop_index(op.f('ix_order_delivery_method'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_manufacturer_manager_phone'), table_name='manufacturer_manager')
    op.drop_index(op.f('ix_manufacturer_manager_email'), table_name='manufacturer_manager')
    op.drop_table('manufacturer_manager')
    op.drop_index(op.f('ix_customer_manager_phone'), table_name='customer_manager')
    op.drop_index(op.f('ix_customer_manager_email'), table_name='customer_manager')
    op.drop_table('customer_manager')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_staff_manager_phone'), table_name='staff_manager')
    op.drop_index(op.f('ix_staff_manager_email'), table_name='staff_manager')
    op.drop_table('staff_manager')
    op.drop_table('permission')
    op.drop_index(op.f('ix_manufacturer_title'), table_name='manufacturer')
    op.drop_index(op.f('ix_manufacturer_street'), table_name='manufacturer')
    op.drop_index(op.f('ix_manufacturer_metro_station'), table_name='manufacturer')
    op.drop_index(op.f('ix_manufacturer_city'), table_name='manufacturer')
    op.drop_table('manufacturer')
    op.drop_index(op.f('ix_customer_title'), table_name='customer')
    op.drop_index(op.f('ix_customer_street'), table_name='customer')
    op.drop_index(op.f('ix_customer_metro_station'), table_name='customer')
    op.drop_index(op.f('ix_customer_city'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('category')
    # ### end Alembic commands ###
